/* sm83_netlist_data.h  -- AUTO-GENERATED by tools/jelib_extractor.py -- DO NOT EDIT */
#pragma once
#include <stdint.h>

/* Layer IDs */
#define SM83_LAYER_METAL1  0
#define SM83_LAYER_POLY  1
#define SM83_LAYER_NACTIVE  2
#define SM83_LAYER_PACTIVE  3
#define SM83_LAYER_NTRANS  4
#define SM83_LAYER_PTRANS  5

/* Counts */
#define SM83_TRANSISTOR_COUNT  9250
#define SM83_NODE_COUNT        66749
#define SM83_ARC_COUNT         86726
#define SM83_NET_COUNT         15440
#define SM83_INSTANCE_COUNT    663

/* Die bounding box (Electric VLSI units) */
#define SM83_BBOX_X_MIN  0.00f
#define SM83_BBOX_X_MAX  3670.00f
#define SM83_BBOX_Y_MIN  0.00f
#define SM83_BBOX_Y_MAX  3383.00f

/* Per-layer index ranges into sm83_transistors[] (sorted by layer) */
#define SM83_TRANS_METAL1_START  0
#define SM83_TRANS_METAL1_END    0
#define SM83_TRANS_POLY_START  0
#define SM83_TRANS_POLY_END    0
#define SM83_TRANS_NACTIVE_START  0
#define SM83_TRANS_NACTIVE_END    0
#define SM83_TRANS_PACTIVE_START  0
#define SM83_TRANS_PACTIVE_END    0
#define SM83_TRANS_NTRANS_START  0
#define SM83_TRANS_NTRANS_END    6094
#define SM83_TRANS_PTRANS_START  6094
#define SM83_TRANS_PTRANS_END    9250

/* Per-layer index ranges into sm83_nodes[] (sorted by layer) */
#define SM83_NODE_METAL1_START  0
#define SM83_NODE_METAL1_END    66749
#define SM83_NODE_POLY_START  0
#define SM83_NODE_POLY_END    0
#define SM83_NODE_NACTIVE_START  0
#define SM83_NODE_NACTIVE_END    0
#define SM83_NODE_PACTIVE_START  0
#define SM83_NODE_PACTIVE_END    0
#define SM83_NODE_NTRANS_START  0
#define SM83_NODE_NTRANS_END    0
#define SM83_NODE_PTRANS_START  0
#define SM83_NODE_PTRANS_END    0

/* Per-layer index ranges into sm83_arcs[] (sorted by layer) */
#define SM83_ARC_METAL1_START  0
#define SM83_ARC_METAL1_END    27520
#define SM83_ARC_POLY_START  27520
#define SM83_ARC_POLY_END    55388
#define SM83_ARC_NACTIVE_START  55388
#define SM83_ARC_NACTIVE_END    74559
#define SM83_ARC_PACTIVE_START  74559
#define SM83_ARC_PACTIVE_END    86726
#define SM83_ARC_NTRANS_START  0
#define SM83_ARC_NTRANS_END    0
#define SM83_ARC_PTRANS_START  0
#define SM83_ARC_PTRANS_END    0

/* Power rail candidates identified by find_power_rails.py (heuristic, not confirmed by name).
 * GND: net@277 (id=270) — 219 N-trans terminals, 1 P-trans terminal, ratio 219:1.
 * VCC: net@28  (id=25)  — 84  P-trans terminals, 6  N-trans terminals, ratio 14:1.
 *      (Previous best was net@35/id=32, ratio 3.9:1 — corrected after deeper analysis.)
 * Status: HEURISTIC — not confirmed by die inspection yet. */
#define SM83_GND_NET_HEURISTIC   270  /* net@277: n=219 p=1  arcs=155 — best GND ratio 219:1 */
#define SM83_VCC_NET_HEURISTIC    25  /* net@28:  n=6   p=84 arcs=349 — best VCC ratio 14:1  */
/* Runners-up: GND: 226(net@228 n=216 p=17 ratio=12.7), 243(net@245 n=179 p=2 ratio=89.5) */
/* Runners-up: VCC:  31(net@34  n=22  p=93 ratio=4.2),  32(net@35  n=25  p=97 ratio=3.9)  */

/* Transistor: normalized position and size (nx,ny,nw,nh in [0,1]), layer (0=ntrans,1=ptrans).
 * gate_net/s1_net/s2_net are indices into sm83_nets[]; -1 = unresolved. */
typedef struct {
    float nx, ny;     /* normalized die coordinates (center) */
    float nw, nh;     /* normalized width/height */
    float x, y;       /* raw Electric VLSI units */
    float w, h;       /* raw width/height */
    uint8_t layer;    /* SM83_LAYER_NTRANS or SM83_LAYER_PTRANS */
    int32_t gate_net; /* index into sm83_nets[], -1 = unknown */
    int32_t s1_net;   /* source/drain net 1, -1 = unknown */
    int32_t s2_net;   /* source/drain net 2, -1 = unknown */
} Sm83Transistor;

/* Geometry node (contact, pin, active area, poly, metal pin) */
typedef struct {
    float nx, ny;   /* normalized die coordinates (center) */
    float nw, nh;   /* normalized width/height */
    float x, y;     /* raw Electric VLSI units */
    float w, h;     /* raw width/height */
    uint8_t layer;
} Sm83Node;

/* Arc (wire segment between two nodes) */
typedef struct {
    float ntx, nty, nhx, nhy;    /* normalized tail/head positions */
    float tx, ty, hx, hy;         /* raw coordinates */
    float width;
    uint8_t layer;
    int32_t tail_node, head_node; /* indices into sm83_nodes[], -1 if unknown */
    int32_t net_id;               /* index into sm83_nets[], -1 if unknown */
} Sm83Arc;

/* Named instance (sub-cell placement in top-level die) */
typedef struct {
    float nx, ny;
    float x, y;
    const char *name;
    const char *cell;
} Sm83Instance;

extern const Sm83Transistor sm83_transistors[SM83_TRANSISTOR_COUNT];
extern const Sm83Node       sm83_nodes[SM83_NODE_COUNT];
extern const Sm83Arc        sm83_arcs[SM83_ARC_COUNT];
extern const char * const   sm83_nets[SM83_NET_COUNT];
extern const Sm83Instance   sm83_instances[SM83_INSTANCE_COUNT];
