/* lcd_schematic_map.h — Semantic mapping for the DMG LCD board (DMG-LCD-06).
 *
 * Net and component indices are stable relative to lcd_schematic_data.c/h
 * generated by kicad_extractor.py --prefix LCD from DMG-LCD-06.kicad_sch
 * (Gekkio, CC BY 4.0).
 *
 * This board carries:
 *   U2 (LH5076)  — LCD row driver
 *   U3 (LH5077)  — LCD column driver
 *   U1 (IR3E02)  — LCD bias voltage generator
 *   VR1 (30k)    — contrast potentiometer
 *   J2            — ribbon cable to main board (LCD signals)
 *   J1            — ribbon cable to main board (joypad / speaker)
 *   LS1 / DA1-4  — speaker + diode bridge
 *   SW1-SW8       — button switches (joypad)
 *   J3-J5         — joypad sub-board connectors
 */
#pragma once
#include "hw_schematic_map.h"
#include "lcd_schematic_data.h"

/* -------------------------------------------------------------------------
 * Tables — defined in lcd_schematic_map.c
 * ------------------------------------------------------------------------- */
extern const HwNetSemantic       lcd_net_map[];
extern const HwComponentSemantic lcd_component_map[];
extern const int                 lcd_net_map_count;
extern const int                 lcd_component_map_count;
