/* lcd_schematic_data.h -- AUTO-GENERATED by tools/kicad_extractor.py -- DO NOT EDIT */
/* Source: https://github.com/Gekkio/gb-schematics (CC-BY 4.0) */
/* Attribution: Joonas Javanainen (Gekkio), CC BY 4.0 */
/* Generated : 2026-06-28T18:56:36Z */
/* Source    : DMG-LCD-06.kicad_sch */
/* SHA-256   : DMG-LCD-06.kicad_sch:a1a049e62d79587b */
/* Counts    : components=46 wires=266 nets=59 labels=73 junctions=41 */
#pragma once
#include <stdint.h>
#include "hw_schematic_data.h"

#define LCD_COMPONENT_COUNT  46
#define LCD_WIRE_COUNT       266
#define LCD_NET_COUNT        59
#define LCD_LABEL_COUNT      73
#define LCD_JUNCTION_COUNT   41

extern const HwComponent lcd_components[LCD_COMPONENT_COUNT];
extern const HwWire      lcd_wires[LCD_WIRE_COUNT];
extern const HwNet       lcd_nets[LCD_NET_COUNT];
extern const HwLabel     lcd_labels[LCD_LABEL_COUNT];
extern const HwJunction  lcd_junctions[LCD_JUNCTION_COUNT];
