/* lcd_schematic_map.c — Semantic mapping for DMG-LCD-06 (Gekkio, CC BY 4.0).
 *
 * Net ids come from lcd_schematic_data.c generated by kicad_extractor.py.
 * Columns: net_id, schematic_name, canonical_name, kind, bit, active_low, conf
 *
 * LCD board signal groups:
 *   LCD control  : FR, S, ST, CP, CPL, CPG, LD0, LD1 (row/col drivers U2/U3)
 *   LCD bias     : V1-V5, VEE (generated by bias IC U1 / IR3E02)
 *   Joypad       : P10-P15, P10_J3, P10_J5, P12_J4 (button matrix)
 *   Joypad dir   : U, D, L, R, A, B, Start, Select (button nets)
 *   Audio        : SPKOUT, SP1 (speaker output)
 *   Power        : VCC, VDD, GND
 *   Connectors   : J1 (main board), J2 (LCD ribbon), J3-J5 (joypad sub-boards)
 */
#include "lcd_schematic_map.h"
#include <stddef.h>

#define CONF HW_CONF_CONFIRMED
#define PROB HW_CONF_PROBABLE
#define PROX HW_CONF_PROXY
#define UNK  HW_CONF_UNKNOWN

const HwNetSemantic lcd_net_map[] = {

    /* Power rails */
    { 0,  "VCC",    "VCC",    HW_SIG_POWER,  -1, false, CONF },
    { 42, "VDD",    "VDD",    HW_SIG_POWER,  -1, false, CONF },
    { 16, "GND",    "GND",    HW_SIG_POWER,  -1, false, CONF },

    /* LCD bias voltages — generated by U1 (IR3E02) controlled by VR1 */
    { 11, "V1",     "V1",     HW_SIG_POWER,  -1, false, CONF },
    { 13, "V2",     "V2",     HW_SIG_POWER,  -1, false, CONF },
    {  5, "V3",     "V3",     HW_SIG_POWER,  -1, false, CONF },
    { 25, "V4",     "V4",     HW_SIG_POWER,  -1, false, CONF },
    { 29, "V5",     "V5",     HW_SIG_POWER,  -1, false, CONF },
    { 22, "VEE",    "VEE",    HW_SIG_LCD,    -1, false, CONF }, /* LCD contrast/bias */

    /* LCD row driver signals (U2 = LH5076) */
    {  1, "FR",     "FR",     HW_SIG_LCD,    -1, false, CONF },
    {  2, "S",      "S",      HW_SIG_LCD,    -1, false, CONF },
    {  8, "ST",     "ST",     HW_SIG_LCD,    -1, false, CONF },
    { 15, "CPL",    "CPL",    HW_SIG_LCD,    -1, false, CONF },

    /* LCD column driver signals (U3 = LH5077) */
    { 28, "LD0",    "LD0",    HW_SIG_LCD,    0,  false, CONF },
    { 36, "LD1",    "LD1",    HW_SIG_LCD,    1,  false, CONF },
    { 37, "CP",     "CP",     HW_SIG_LCD,    -1, false, CONF },
    { 48, "CPG",    "CPG",    HW_SIG_LCD,    -1, false, CONF },

    /* Joypad matrix lines on main connector (P1x from CPU) */
    { 23, "P10",    "P10",    HW_SIG_JOYPAD, 0,  false, CONF },
    { 46, "P11",    "P11",    HW_SIG_JOYPAD, 1,  false, CONF },
    { 53, "P12",    "P12",    HW_SIG_JOYPAD, 2,  false, CONF },
    {  4, "P13",    "P13",    HW_SIG_JOYPAD, 3,  false, CONF },
    { 31, "P14",    "P14",    HW_SIG_JOYPAD, 4,  false, CONF },
    { 30, "P15",    "P15",    HW_SIG_JOYPAD, 5,  false, CONF },

    /* Joypad matrix lines on sub-board connectors (J3/J4/J5) */
    { 17, "P10_J3", "P10_J3", HW_SIG_JOYPAD, 0,  false, PROB },
    { 27, "P10_J5", "P10_J5", HW_SIG_JOYPAD, 0,  false, PROB },
    {  9, "P12_J4", "P12_J4", HW_SIG_JOYPAD, 2,  false, PROB },

    /* Button output nets (column lines from diode matrix) */
    { 44, "D",      "Down",   HW_SIG_JOYPAD, -1, false, CONF },
    { 45, "R",      "Right",  HW_SIG_JOYPAD, -1, false, CONF },
    { 14, "L",      "Left",   HW_SIG_JOYPAD, -1, false, CONF },
    { 12, "U",      "Up",     HW_SIG_JOYPAD, -1, false, CONF },
    { 32, "A",      "A",      HW_SIG_JOYPAD, -1, false, CONF },
    { 41, "B",      "B",      HW_SIG_JOYPAD, -1, false, CONF },
    { 24, "Start",  "Start",  HW_SIG_JOYPAD, -1, false, CONF },
    {  3, "Select", "Select", HW_SIG_JOYPAD, -1, false, CONF },

    /* LCD driver supply (DVDD = VDD local for U2/U3, from main VDD) */
    { 19, "DVDD",   "DVDD",   HW_SIG_POWER,  -1, false, CONF },

    /* Audio */
    { 52, "SPKOUT", "SPKOUT", HW_SIG_AUDIO,  -1, false, CONF },
    { 39, "SP1",    "SP1",    HW_SIG_AUDIO,  -1, false, CONF },

    /* Bus from main board (P1[0..3] combined net — schematic grouping proxy) */
    { 58, "P1[0..3]", "P1[0..3]", HW_SIG_JOYPAD, -1, false, PROX },
};

const int lcd_net_map_count =
    (int)(sizeof(lcd_net_map) / sizeof(lcd_net_map[0]));

/* -------------------------------------------------------------------------
 * Component semantic table
 *
 * Columns: comp_id, ref, value, kind, emulator_owner, confidence
 * ------------------------------------------------------------------------- */
const HwComponentSemantic lcd_component_map[] = {

    /* LCD drivers */
    { 11, "U2",  "LH5076",     HW_COMP_PPU_LCD,   "gb->ppu",         CONF },
    { 12, "U3",  "LH5077",     HW_COMP_PPU_LCD,   "gb->ppu",         CONF },

    /* LCD bias IC + contrast pot */
    {  6, "U1",  "IR3E02",     HW_COMP_PPU_LCD,   "gb->ppu (bias)",  CONF },
    {  4, "VR1", "30k",        HW_COMP_PPU_LCD,   "contrast",        CONF },

    /* Main board connectors */
    {  7, "J2",  "Wire",       HW_COMP_PPU_LCD,   "LCD ribbon",      CONF },
    { 10, "J1",  "Wire",       HW_COMP_APU_AUDIO, "main board",      CONF },
    {  0, "A1",  "Ribbon cable", HW_COMP_PPU_LCD, "LCD ribbon",      CONF },

    /* Joypad sub-board connectors */
    { 43, "J3",  "Wire",       HW_COMP_JOYPAD,    "joypad sub-board", CONF },
    { 44, "J5",  "Wire",       HW_COMP_JOYPAD,    "joypad sub-board", CONF },
    { 45, "J4",  "Wire",       HW_COMP_JOYPAD,    "joypad sub-board", CONF },

    /* Button switches */
    { 29, "SW6", "Start",      HW_COMP_JOYPAD,    "gb->joypad",      CONF },
    { 30, "SW5", "Select",     HW_COMP_JOYPAD,    "gb->joypad",      CONF },
    { 31, "SW7", "B",          HW_COMP_JOYPAD,    "gb->joypad",      CONF },
    { 32, "SW8", "A",          HW_COMP_JOYPAD,    "gb->joypad",      CONF },
    { 33, "SW1", "Left",       HW_COMP_JOYPAD,    "gb->joypad",      CONF },
    { 34, "SW4", "Right",      HW_COMP_JOYPAD,    "gb->joypad",      CONF },
    { 35, "SW2", "Up",         HW_COMP_JOYPAD,    "gb->joypad",      CONF },
    { 36, "SW3", "Down",       HW_COMP_JOYPAD,    "gb->joypad",      CONF },

    /* Speaker + diode bridge */
    {  9, "LS1", "8 ohm",      HW_COMP_APU_AUDIO, "gb->apu",         CONF },
    { 39, "DA1", "DAN215",     HW_COMP_APU_AUDIO, "speaker bridge",  PROB },
    { 40, "DA2", "DAN215",     HW_COMP_APU_AUDIO, "speaker bridge",  PROB },
    { 41, "DA3", "DAN215",     HW_COMP_APU_AUDIO, "speaker bridge",  PROB },
    { 42, "DA4", "DAN215",     HW_COMP_APU_AUDIO, "speaker bridge",  PROB },

    /* Decoupling / passives (grouped as MISC) */
    {  1, "R1",  "1k",         HW_COMP_MISC,      NULL,              PROB },
    { 19, "R2",  "100R",       HW_COMP_MISC,      NULL,              PROB },
    {  2, "D1",  "3.6V",       HW_COMP_MISC,      NULL,              PROB },
    {  3, "D2",  "LED",        HW_COMP_MISC,      NULL,              PROB },
    { 13, "Q1",  "2SA933SR",   HW_COMP_MISC,      NULL,              PROB },
    {  5, "C3",  "10u",        HW_COMP_MISC,      NULL,              PROB },
    {  8, "C1",  "100u",       HW_COMP_MISC,      NULL,              PROB },
    { 14, "C4",  "47p",        HW_COMP_MISC,      NULL,              PROB },
    { 16, "C6",  "1u",         HW_COMP_MISC,      NULL,              PROB },
    { 18, "C8",  "1u",         HW_COMP_MISC,      NULL,              PROB },
    { 22, "C9",  "1u",         HW_COMP_MISC,      NULL,              PROB },
    { 26, "C10", "1u",         HW_COMP_MISC,      NULL,              PROB },
    { 28, "C7",  "1u",         HW_COMP_MISC,      NULL,              PROB },
    { 37, "C2",  "100u",       HW_COMP_MISC,      NULL,              PROB },
    { 38, "C5",  "1200p",      HW_COMP_MISC,      NULL,              PROB },
};

const int lcd_component_map_count =
    (int)(sizeof(lcd_component_map) / sizeof(lcd_component_map[0]));
